#!/bin/bash

ROOT_UID="0"

#Check if run as root
if [ "$UID" -ne "$ROOT_UID" ] ; then
	echo "What? Make it yourself."
	exit 1
else
    echo "Okay."
    echo '
                    _.---._
                _.-~       ~-._
            _.-~               ~-._
        _.-~                       ~---._
    _.-~                                 ~\
 .-~                                    _.;
 :-._                               _.-~./
 }-._~-._                   _..__.-~_.-~ )
 `-._~-._~-._              /   ...-~H.-~
     ~-nad.._\.        _.-~ .::::  //
         ~-. \`--...--~ _.-~__...==~
            \.`--...---+-~~~~~
              ~-..----~'
    exit 0
fi
